# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kioD_nxCSL3jurPQan8TK5MOxKhQxjCG
"""

#Importando a biblioteca
import pandas as pd

#Leitura da fonte de dados
df = pd.read_excel("/content/dataset-vendas.xlsx")

df.head()

#Criando a coluna de receita
df["Receita"] = df["Quantidade"].mul(df["Preço"])

df.head()

#Retornando a maior receira
df["Receita"].max()

#Retornando a menor receita
df["Receita"].min()

#Retornar top 3 maiores receitas (nlargest)
df.nlargest(3, "Receita")

#Retornar top 3 menores receitas (nsamllest)
df.nsmallest(3, "Receita")

#Agrupamento por tipo
df.groupby("Tipo")["Receita"].sum()

#Ordenando o conjunto de dados pela maior receita
df.sort_values("Receita", ascending=False).head(10)

#Ordenando o conjunto de dados
df.sort_values("Nome do produto", ascending=True).head(10)

df["Quantidade"].value_counts(ascending=False).plot.bar()

df["Quantidade"].value_counts(ascending=False).plot.barh()

#Gráfico de pizza
df.groupby(df["Tipo"])["Receita"].sum().plot.pie()

#Adicionando um título e alterando o nome dos eixos
import matplotlib.pyplot as plt

df["Tipo"].value_counts().plot.bar(title="Total vendas por produto")
plt.xlabel("Nome do produto")
plt.ylabel("Receita")

#Alterado a cor
df["Tipo"].value_counts().plot.bar(title="Total vendas por produto", color="red")
plt.xlabel("Nome do produto")
plt.ylabel("Receita")

#Alterado o estilo
plt.style.use("ggplot")

df.groupby(df["Tipo"])["Quantidade"].sum().plot()
plt.xlabel("Tipo")
plt.ylabel("Quantidade de produtos vendidos")
plt.legend